# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nn-zero-to-hero',
                'doc_host': 'https://khankanz.github.io',
                'git_url': 'https://github.com/khankanz/nn-zero-to-hero',
                'lib_path': 'nn_zero_to_hero'},
  'syms': {'nn_zero_to_hero.core': {'nn_zero_to_hero.core.foo': ('core.html#foo', 'nn_zero_to_hero/core.py')}}}
